#ESCUELA POLITECNICA NACIONAL
#ESCUELA DE FORMACION DE TECNOLOGOS
#EXAMEN BIMESTRAL
#PROGRAMACION AVANZADA
#INTEGRANTES.PY
#VERSION 1.0
#INTEGRANTES:
        #CAMPOVERDE VARGAS JORGE CRISTIAN
        #CENTENO ROCHA JOHANA MISHEL
        #MAZA CAÑAR JERSON STALIN
        #PADILLA PERALVO EDISON GEOVANNNY
        #TIBANTA LEGÑA MARIA FERNANDA

def creartxt(nombre):
    archi = open(nombre,"w") #ESTA FUNCION CREA LOS ARCHIVOS DE TEXTO
    archi.close() #RECIBE EL NOMBRE DEL ARCHIVO DE TEXTO
    
def grabartxt(cadena,name):
    archi=open(name,"a") #ESTA FUNCION GRABA LA CADENA EN EL ARCHIVO DE TEXTO
    archi.write(cadena + "\n") #RECIBE EL NOMBRE DEL ARCHIVO DE TEXTO DONDE GRABAR
    archi.close()

def names():
    m1 = "CAMPOVERDE VARGAS JORGE CRISTIAN"
    m2 = "CENTENO ROCHA JOHANA MISHEL"
    m3 = "MAZA CAÑAR JERSON STALIN"  #ESTAS SON CADENAS PEQUEÑAS CON 
    m4 = "PADILLA PERALVO EDISON GEOVANNNY" #LOS NOMBRES DE CADA UNO DE 
    m5 = "TIBANTA LEGÑA MARIA FERNANDA" #LOS INTEGRANRES
    e = " " #CADENA QUE CONTIENE UN ESPACIO
    total = m1 + e + m2 + e + m3 + e + m4 + e + m5 #AQUI SE CONCATENA LOS INTEGRANTES
    return total #AQUI RETORNA LA CADENA FINAL

def main():
    creartxt("nombres.txt")
    creartxt("nombres2.txt") #AQUI CREO LOS ARCHIVOS TXT
    for i in range (690):
        grabartxt(names(),"nombres.txt") #AQUI LLENO EL ARCHIVO REPITIENDO N VECES HASTA Q PESE APROX 100 KB
        
    print("PRIMERO CREADO CORRECTAMENTE") #MENSAJE DE FINALIZACION
    for i in range (7040):
        grabartxt(names(),"nombres2.txt") #AQUI LLENO EL ARCHIVO REPITIENDO N VECES HASTA Q PESE APROX 1024 KB
    print("SEGUNDO CREADO CORRECTAMENTE")#MENSAJE DE FINALIZACION

main()
